library(tidyverse)
BOM_data <- read_csv("BOM_data.csv")
BOM_station <-read_csv("BOM_stations.csv")
BOM_data_separated <- separate(BOM_data,5, into = c ('temp_min',"temp_max"),sep="/")
BOM_data_filtered <- filter(BOM_data_separated,temp_min!="-"& temp_max!="-"& Rainfall!="-"& Solar_exposure!="-")
grouped_data_min <- group_by(BOM_data_filtered,temp_min!="0")

#Q1
#ans_Q1 <-filter(bom_data_sep, min_temp != "-", max_temp != "-", Rainfall != "-" ) %>% 
#group_by(Station_number) %>% summarise(n_days =  n()) 
group_by_station <- group_by(BOM_data_filtered,Station_number)
summarise(group_by_station,num_row=n())

#Q2
group_by_month <- group_by(BOM_data_separated,Month)
group_by_month_f <- group_by(BOM_data_filtered,Month)
temp_diff_mutated <- mutate(group_by_month_f,temp_diff = as.numeric(temp_max) - as.numeric(temp_min))
lowest_mean_monthly <- summarise(temp_diff_mutated,mean=mean(temp_diff))%>% summarise(min=min(mean))
#when using pipe the second commands gets the dataframe from the fisr command and the second cammand works with 
#whatever tibble generated by the first command

#Q3
#which state saw the lowest ave daily temp difference
#need to combine/join data sets to answer next two Qs so saving as new tibble:
#misc arbitary name
BOM_station_data <- BOM_station %>% gather(station_ID,Misc,-info)%>% spread(info,Misc)
gather(BOM_station,station_ID,misc,-info)
#col names are the station ids #misc is the values , info has the row names
#to merege the data the station_ID is character and have to convert to number
BOM_station_data <- mutate(BOM_station_data,station_ID= as.numeric(station_ID))
BOM_station_rename <- rename(BOM_data_filtered,station_ID=Station_number) 
BOM_mereged_data <- full_join(BOM_station_rename,BOM_station_data)
Answer_to_Q3 <- BOM_mereged_data %>% mutate(temp_var=as.numeric(temp_max)-as.numeric(temp_min))%>%
group_by(state) %>% summarise(temp_var=mean(temp_var,na.rm = TRUE)) %>% arrange(temp_var)
#na.rm arrgument remove that are NA ,it ignores the missing values

#Q4
#elise answer
#Does the westmost (lowest longitude) or eastmost (highest longitude) weather station in our 
#dataset have a higher average solar exposure?
answet_to_Q4 <- BOM_mereged_data %>% filter(Solar_exposure!="-")%>% mutate(Solar_exposure=as.numeric(Solar_exposure))%>%
group_by(station_ID,lon)%>% summarise(Solar_exposure=mean(Solar_exposure)) %>% arrange(lon)%>%slice(-2:-n()-1)

#Stephen
BOM_lon_solar_exp <- BOM_mereged_data %>% mutate(Solar_exposure=as.numeric(Solar_exposure))%>% group_by(lon,state,station_ID) %>% 
summarise(av_solar_exp=mean(Solar_exposure,na.rm=TRUE)) %>% ungroup() %>% filter(lon==max(lon)|lon==min(lon)) 




